language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - python -m pytest --cov=anchorman --cov-report term-missing -v -s
after_success:
  - codecov
