language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  pip install codecov
after_success:
  codecov
install:
  - pip install -r requirements.txt
script:
  - python -m pytest -v -s


