language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then coverage run $(which py.test) test --verbose; coverage report --show-missing; else py.test test - -verbose; fi

after_success:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls ; coveralls ; fi

notifications:
  email: true
