language: python
sudo: false
python:
  - "2.7"
# command to install dependencies
install:
  - pip install coveralls python-coveralls coverage
  - pip install -r requirements.txt

script:
    - py.test test --doctest-modules -v --cov coveralls --cov-report term-missing

after_success:
    - coveralls

notifications:
  email: false
