name: anchorman
version: 0.3.3
author: matthias rebel

# optional
author_email: webmaster@rebeling.net
url: https://github.com/rebeling/anchorman
description: Anchorman takes a list of terms and a text. It finds the terms in this text and replaces them with another representation.
license: Apache License
copyright: 2015
keywords:
    - intext
    - link
    - annotation
    - tag
    - hypertext
